# Generated by Django 5.1.6 on 2025-02-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField()),
                ('description', models.TextField()),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'Meetings',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.company')),
            ],
            options={
                'db_table': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_purpose', models.TextField()),
                ('arrival_timestamp', models.DateTimeField(auto_now_add=True)),
                ('leave_timestamp', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.car')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.guest')),
            ],
            options={
                'db_table': 'Arrivals',
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.host')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.meeting')),
            ],
            options={
                'db_table': 'Leaderships',
                'unique_together': {('host', 'meeting')},
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.arrival')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.meeting')),
            ],
            options={
                'db_table': 'Participations',
                'unique_together': {('arrival', 'meeting')},
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.arrival')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='database_models.host')),
            ],
            options={
                'db_table': 'Responsibilities',
                'unique_together': {('host', 'arrival')},
            },
        ),
    ]
