# Generated by Django 5.1.6 on 2025-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='host',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='host',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
