# Generated by Django 5.1.6 on 2025-02-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0002_alter_responsibility_host_alter_leadership_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='company',
        ),
        migrations.AddField(
            model_name='arrival',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='database_models.company'),
        ),
    ]
