# Generated by Django 5.1.6 on 2025-02-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0003_remove_guest_company_arrival_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='database_models.car'),
        ),
    ]
