# Generated by Django 5.1.6 on 2025-02-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0004_alter_arrival_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
