# Generated by Django 5.1.6 on 2025-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0005_delete_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='meetings',
            field=models.ManyToManyField(to='database_models.meeting'),
        ),
    ]
