# Generated by Django 5.1.6 on 2025-02-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0006_arrival_meetings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='meetings',
        ),
        migrations.DeleteModel(
            name='Leadership',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
