# Generated by Django 5.1.6 on 2025-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_models', '0007_remove_arrival_meetings_delete_leadership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrival',
            name='arrival_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
